export { Sidebar } from "./components/sidebar";
export { SidebarShell } from "./components/sidebar-shell";
export type { MainNavItem, NestedNavItem } from "./components/sidebar-shell";
export { SidebarItemLink } from "./components/sidebar-item-link";
export { BreadcrumbsNav } from "./components/breadcrumbs-nav";
export * from "./lib/sidebar-registry-resolver";
export * from "./lib/breadcrumb-utils";
export * from "./lib/breadcrumb-registry";
export * from "./lib/generated-sidebar-registry";
export * from "./lib/generated-breadcrumb-registry";
export { useBreadcrumbs } from "./hooks/use-breadcrumbs";
export { useSidebarSearch } from "./hooks/use-sidebar-search";
export { useSidebarScroll, SidebarItemLink as SidebarItemLinkUtil, type SidebarSection } from "./lib/sidebar-utils";
