// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'header-basic': { variationKey: '01-basic', exportName: 'BasicHeader' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
