// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'chat-basic': { variationKey: '01-basic', exportName: 'BasicChat' },
  'chat-with-actions': { variationKey: '02-with-actions', exportName: 'ChatWithActions' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
