// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'toc-basic': { variationKey: '01-basic', exportName: 'BasicTOC' },
  'toc-expanded': { variationKey: '02-expanded', exportName: 'ExpandedTOC' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
