// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'aichatinput-basic': { variationKey: '01-basic', exportName: 'BasicAIChatInput' },
  'aichatinput-with-suggestions': { variationKey: '02-with-suggestions', exportName: 'AIChatInputWithSuggestions' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
