// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'teststructure-nested-structure': { variationKey: '01-nested-structure', exportName: 'NestedTestStructure' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
