// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'chainofthought-basic': { variationKey: '01-basic', exportName: 'BasicChainOfThought' },
  'chainofthought-with-details': { variationKey: '02-with-details', exportName: 'ChainOfThoughtWithDetails' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
