import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface Variation {
  name: string;
  description: string;
  demoPath: string;
  exportName: string;
  files: any[];
}

function getElementPreviewComponent(elementName: string): string {
  switch (elementName) {
    case 'Header':
      return `function HeaderPreview() {
  return (
    <header className="bg-background-800 border-b border-background-700 w-full">
      <div className="px-4 py-3 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-1">
          <div className="w-6 h-6 bg-accent-500 rounded-base flex-shrink-0" />
          <div className="w-16 h-4 bg-background-700 rounded flex-shrink-0" />
        </div>
        <div className="flex items-center gap-2">
          <div className="w-8 h-3 bg-background-700 rounded flex-shrink-0" />
          <div className="w-8 h-3 bg-background-700 rounded flex-shrink-0" />
          <div className="w-px h-5 bg-background-700" />
          <button className="p-2 text-foreground-400 hover:text-foreground-300 hover:bg-background-700 rounded transition-colors flex-shrink-0">
            <FaBell className="w-4 h-4" />
          </button>
          <button className="p-2 text-foreground-400 hover:text-foreground-300 hover:bg-background-700 rounded transition-colors flex-shrink-0">
            <FaGear className="w-4 h-4" />
          </button>
          <button className="p-2 text-foreground-400 hover:text-foreground-300 hover:bg-background-700 rounded transition-colors flex-shrink-0">
            <FaUser className="w-4 h-4" />
          </button>
        </div>
      </div>
    </header>
  );
}`;
    case 'Sidebar':
      return `function SidebarPreview() {
  return (
    <aside className="w-64 bg-background-900 border-r border-background-700 min-h-screen">
      <div className="p-4 space-y-6">
        <div className="w-10 h-10 bg-accent-500 rounded-md flex-shrink-0" />
        <nav className="space-y-2">
          <div className="h-3 bg-background-700 rounded w-4/5" />
          <div className="h-3 bg-background-700 rounded w-3/4" />
          <div className="h-3 bg-background-700 rounded w-4/5" />
        </nav>
      </div>
    </aside>
  );
}`;
    case 'Page':
      return `function PagePreview() {
  return (
    <div className="min-h-screen bg-background-950 p-6">
      <div className="space-y-4">
        <div className="h-8 bg-background-700 rounded w-1/4" />
        <div className="space-y-2">
          <div className="h-3 bg-background-700 rounded w-full" />
          <div className="h-3 bg-background-700 rounded w-5/6" />
        </div>
      </div>
    </div>
  );
}`;
    default:
      return `function ${elementName}Preview() {
  return <div>Preview for ${elementName}</div>;
}`;
  }
}

function generatePreviewFile(
  elementName: string,
  variations: Record<string, Variation>
): string {
  const capitalizedName =
    elementName.charAt(0).toUpperCase() + elementName.slice(1);
  const lowerName = elementName.toLowerCase();

  const sortedVariations = Object.entries(variations).sort(
    ([keyA], [keyB]) => keyA.localeCompare(keyB)
  );

  const imports = sortedVariations
    .map(([key, variation]) => `import { ${variation.exportName} } from './variations/${key}';`)
    .join('\n');

  const needsFaIcons =
    elementName === 'Header' || sortedVariations.some(([, v]) => v.exportName.includes('Button'));
  const faImport = needsFaIcons
    ? `import { FaBell, FaGear, FaUser } from 'react-icons/fa6';\n`
    : '';

  const variationComponentMap = sortedVariations
    .map(([key, variation]) => `  '${key}': ${variation.exportName},`)
    .join('\n');

  const namedExports = sortedVariations
    .map(([, variation]) => variation.exportName)
    .join(', ');

  const previewComponent = getElementPreviewComponent(elementName);

  return `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-preview-files.ts
// To regenerate: pnpm generate
// To modify: Update variation files and metadata in index.ts, then regenerate

import React from 'react';
${faImport}import variationsGenerated from './variations.json';
import type { ElementMetadata, LayoutConfig } from '../../types';
${imports}

${previewComponent}

const variationComponentMap = {
${variationComponentMap}
};

export const demoComponents = {
  '${lowerName}-preview': ${capitalizedName}Preview,
  ...Object.entries(variationsGenerated).reduce(
    (acc, [key, variation]: any) => ({
      ...acc,
      [variation.demoPath]: variationComponentMap[key as keyof typeof variationComponentMap],
    }),
    {} as Record<string, React.ComponentType<object>>
  ),
};

export { ${namedExports}, ${capitalizedName}Preview };
`;
}

async function main() {
  try {
    const elementsPath = path.join(__dirname, '..', 'src', 'elements');
    const elements = fs
      .readdirSync(elementsPath)
      .filter(
        (f) =>
          fs.statSync(path.join(elementsPath, f)).isDirectory() &&
          !f.startsWith('.')
      )
      .sort();

    console.log('\n📝 Generating preview files...\n');

    for (const elementName of elements) {
      const elementPath = path.join(elementsPath, elementName);
      const variationsPath = path.join(elementPath, 'variations.json');
      const previewPath = path.join(elementPath, `${elementName}.preview.tsx`);

      if (!fs.existsSync(variationsPath)) {
        console.warn(`  ⚠️  No variations.json found for ${elementName}, skipping`);
        continue;
      }

      const variations = JSON.parse(fs.readFileSync(variationsPath, 'utf-8'));
      const previewContent = generatePreviewFile(elementName, variations);

      fs.writeFileSync(previewPath, previewContent);
      console.log(`  ✓ ${elementName}.preview.tsx`);
    }

    console.log('\n✅ Preview file generation complete!\n');
  } catch (error) {
    console.error(
      '\n❌ Error during preview generation:',
      error instanceof Error ? error.message : String(error)
    );
    process.exit(1);
  }
}

main();
