import { access, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const registryRoot = path.resolve(__dirname, '..');
const libraryRoot =
  process.env.UI_LAB_PRIVATE_LIBRARY_ROOT ??
  path.resolve(registryRoot, '../../../private/packages/library');
const catalogEntry = path.join(libraryRoot, 'dist', 'catalog.js');
const outputPath = path.join(registryRoot, 'src', 'generated', 'catalog-snapshot.ts');

async function exists(target: string) {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
}

function serialize(value: unknown) {
  // Drops functions (e.g. package getPreview) — the snapshot is plain data.
  return JSON.stringify(value, null, 2);
}

async function main() {
  if (!(await exists(libraryRoot))) {
    console.warn('[catalog-snapshot] Private library not found; keeping committed snapshot.');
    return;
  }

  if (!(await exists(catalogEntry))) {
    throw new Error(
      `[catalog-snapshot] ${catalogEntry} is missing. Build @ui-lab-core/library before generating the registry.`
    );
  }

  const catalog = await import(pathToFileURL(catalogEntry).href);

  const snapshot = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate-catalog-snapshot.ts from @ui-lab-core/library/catalog.
// Plain-data snapshot: metadata only, no preview components (package getPreview is omitted).

import type {
  ElementRegistry,
  ElementPackageRegistry,
  SectionRegistry,
  PatternRegistry,
  StarterRegistry,
} from '../types.js';
import type {
  ElementCategoryId,
  ElementCategoryDefinition,
  SectionCategoryId,
  SectionCategoryDefinition,
} from '../catalog-types.js';

export const elementRegistry: ElementRegistry = ${serialize(catalog.elementRegistry)};

export const elementCategories: Record<ElementCategoryId, ElementCategoryDefinition> = ${serialize(catalog.elementCategories)};

export const elementCategoryMapping: Record<string, ElementCategoryId> = ${serialize(catalog.elementCategoryMapping)};

export const elementPackages: ElementPackageRegistry = ${serialize(catalog.elementPackages)};

export const elementOrder: Record<ElementCategoryId, string[]> = ${serialize(catalog.elementOrder)};

export const sectionRegistry: SectionRegistry = ${serialize(catalog.sectionRegistry)};

export const sectionCategories: Record<SectionCategoryId, SectionCategoryDefinition> = ${serialize(catalog.sectionCategories)};

export const patternRegistry: PatternRegistry = ${serialize(catalog.patternRegistry)};

export const starterRegistry: StarterRegistry = ${serialize(catalog.starterRegistry)};
`;

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, snapshot);
  console.log(
    `[catalog-snapshot] Wrote ${path.relative(registryRoot, outputPath)} ` +
      `(${Object.keys(catalog.elementRegistry).length} elements, ` +
      `${Object.keys(catalog.sectionRegistry).length} sections, ` +
      `${Object.keys(catalog.patternRegistry).length} patterns, ` +
      `${Object.keys(catalog.starterRegistry).length} starters)`
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
