// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate-manifest.ts
// To regenerate: pnpm generate

export const DEMO_PATH_MAP = {
  'nextarticle-basic': { variationKey: '01-basic', exportName: 'BasicNextArticle' },
  'nextarticle-with-icon': { variationKey: '02-with-icon', exportName: 'NextArticleWithIcon' },
} as const;

export type DemoPaths = keyof typeof DEMO_PATH_MAP;
