declare const styles: {
  select: string;
  trigger: string;
  "search-trigger": string;
  "search-value-section": string;
  "search-trigger-input": string;
  "search-content-input": string;
  "search-icon-section": string;
  "search-wrapper": string;
  "value-section": string;
  "icon-section": string;
  icon: string;
  value: string;
  "value-icon": string;
  "value-text": string;
  "value-chevron": string;
  content: string;
  viewport: string;
  list: string;
  item: string;
  "item-icon": string;
  "item-indicator": string;
  "item-text": string;
  "item-content": string;
  "item-description": string;
  "item-with-description": string;
  "item-icon-with-description": string;
  "item-indicator-with-description": string;
  separator: string;
  "scroll-button": string;
  placeholder: string;
  "icon-prefix": string;
  "sub-trigger": string;
  "sub-trigger-chevron": string;
  "sub-content": string;
};

export default styles;
