declare const styles: {
  select: string;
  trigger: string;
  "value-section": string;
  "icon-section": string;
  icon: string;
  value: string;
  "value-icon": string;
  "value-text": string;
  "value-chevron": string;
  content: string;
  viewport: string;
  list: string;
  item: string;
  "item-icon": string;
  "item-indicator": string;
  "item-text": string;
  "item-content": string;
  "item-description": string;
  "item-with-description": string;
  "item-icon-with-description": string;
  "item-indicator-with-description": string;
  separator: string;
  "scroll-button": string;
  placeholder: string;
  "icon-prefix": string;
  subTrigger: string;
  subTriggerChevron: string;
  subContent: string;
};

export default styles;
